name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'cicdlearnpurpose'
          heroku_email: 'baluszynskidawid@gmail.com'
          healthcheck: 'https://cicdlearnpurpose.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true
